"""empty message

Revision ID: 00733427b68d
Revises: dd976a210cfd
Create Date: 2024-11-04 14:44:55.953934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00733427b68d'
down_revision = 'dd976a210cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessories_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['accessories_id'], ['accessories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activewear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activewear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activewear_id'], ['activewear_tops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bottoms_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bottoms_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bottoms_id'], ['bottoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compression_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compression_wear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['compression_wear_id'], ['compression_wear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footwear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footwear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['footwear_id'], ['footwear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outerwear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outerwear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['outerwear_id'], ['outerwear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protective_gear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protective_gear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protective_gear_id'], ['protective_gear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_id'], ['recovery_and_wellness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialty_sportswear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty_sportswear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_sportswear_id'], ['specialty_sportswear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swimwear_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swimwear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('for_gender', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['swimwear_id'], ['swimwear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swimwear_subcategories')
    op.drop_table('specialty_sportswear_subcategories')
    op.drop_table('recovery_subcategories')
    op.drop_table('protective_gear_subcategories')
    op.drop_table('outerwear_subcategories')
    op.drop_table('footwear_subcategories')
    op.drop_table('compression_subcategories')
    op.drop_table('bottoms_subcategories')
    op.drop_table('activewear_subcategories')
    op.drop_table('accessories_subcategories')
    # ### end Alembic commands ###
