"""empty message

Revision ID: 2431fb0c8164
Revises: fdf5db6c0889
Create Date: 2024-11-11 15:07:56.879345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2431fb0c8164'
down_revision = 'fdf5db6c0889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_generated', sa.DateTime(), nullable=False),
    sa.Column('most_popular_product_id', sa.Integer(), nullable=False),
    sa.Column('most_popular_product_type', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('inventory_turnover', sa.Float(), nullable=False),
    sa.Column('future_demand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('most_popular_product_id', sa.INTEGER(), nullable=False),
    sa.Column('most_popular_product_type', sa.VARCHAR(), nullable=False),
    sa.Column('future_demand', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('report')
    # ### end Alembic commands ###
